apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-ingress-external
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Ssl on;
spec:
  ingressClassName: nginx-external
  rules:
    - host: {{ .Values.ingress.domainPrefix }}.{{ .Values.global.domain.public.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}